name: wakelock
description: Plugin that allows you to keep the device screen awake, i.e. prevent the screen from sleeping on
  Android, iOS, macOS, Windows, and web.


environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.9.1

  wakelock_platform_interface: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  pigeon: ^1.0.2 # flutter pub run pigeon --input "pigeons/messages.dart"

flutter:
  plugin:
    platforms:
      android:
        package: creativemaybeno.wakelock
        pluginClass: WakelockPlugin
      ios:
        pluginClass: WakelockPlugin
